
const STORE_TOKEN = "TOKEN";
const STORE_USERID = "USERID";
const AUTH_START = "AUTH_START";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";
const AUTH_LOGOUT = "AUTH_LOGOUT";
export {STORE_TOKEN,STORE_USERID,AUTH_START,AUTH_FAIL,
    AUTH_SUCCESS,AUTH_LOGOUT}