
const STORE_TOKEN = "TOKEN";
const STORE_USERID = "USERID";
const AUTH_START = "AUTH_START";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";
const AUTH_LOGOUT = "AUTH_LOGOUT";
const ACCOUNT_REGISTER = "ACCOUNT_REGISTER";
const ACCOUNT_REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS";
const ACCOUNT_REGISTER_FAIL = "ACCOUNT_REGISTER_FAIL";
export {STORE_TOKEN,STORE_USERID,AUTH_START,AUTH_FAIL,
    AUTH_SUCCESS,AUTH_LOGOUT,ACCOUNT_REGISTER,ACCOUNT_REGISTER_FAIL,ACCOUNT_REGISTER_SUCCESS }